@SistemaSeguimientoEncomiendasAPI_HostAddress = http://localhost:5298

### Obtener todos los clientes
GET {{SistemaSeguimientoEncomiendasAPI_HostAddress}}/api/Clientes
Accept: application/json

###

### Obtener todos los paquetes
GET {{SistemaSeguimientoEncomiendasAPI_HostAddress}}/api/Paquetes
Accept: application/json